### ISSUE TITLE
Question on the eval dataset

### ISSUE THREAD

**Issue by imamnurby** [antonio-mastropaolo/code-summarization-metric#2]
Dear authors, thanks for your amazing work!

I have a question regarding the eval dataset.
![image](https://github.com/antonio-mastropaolo/code-summarization-metric/assets/43092949/d60946eb-8c84-472a-999a-1549d783419c)

Why the "pos" only contains 1 char? is this a bug when you save the dataset? Please kindly advise.
As I understand, the "pos" is the ground truth summary.

*edit 1: typo
*edit 2: fix wording

**Comment by antonio-mastropaolo** [comment]
Hello @imamnurby ,

I'm glad you found our work to be engaging.
Regarding the issue you previously mentioned, I've updated the GDrive folder by replacing the old JSON file with the correct one, which includes the proper "Positive Example" for the evaluation dataset that we used.

Cheers :)
